### PR TITLE
Dropbox v2

### PR DESCRIPTION
**Pull request by mattearnshaw**
the old dropbox API is no longer supported. I'm still testing this but it seems to work. Opening pull request now mainly so I can make a note of the black magic that was required to get virgo to boot:

- clone https://github.com/justinedelson/dropbox-sdk-java 
- checkout branch `feature/better-osgi-citizen`
- `./update-submodules.sh`
- `sudo -H python -m pip install ply six typing`
- apply [this diff](https://gist.github.com/mattearnshaw/10f02a16415eeb38c46e3a587f1121ed)
- `./gradlew -Posgi.bnd.noee=true jar`
- `./gradlew install`

### CODE REVIEW

**Comment by mattearnshaw** [comment]
will have to wait for this to be merged before travis builds https://github.com/dropbox/dropbox-sdk-java/pull/159

**Comment by jrmartin** [comment]
@mattearnshaw Hey Matt. Where did you get the dependencies for dropbox 3.0.6-SNAPSHOT? 

Not found on the maven dependency repository: 
<groupId>com.dropbox.core</groupId>
<artifactId>dropbox-core-sdk</artifactId>
<version>3.0.6-SNAPSHOT</version>

**Comment by jrmartin** [comment]
@mattearnshaw Ah i see now it was done through those steps you provided. Any chance you could upload the generated 3.0.6-SNAPSHOT jars and files to org.geppetto.maven repository? We would have a place to pull the snapshot from without having to wait for that dropbox/dropbox-sdk-java#159 merge to happen

**Comment by mattearnshaw** [comment]
@jrmartin done https://github.com/openworm/org.geppetto.maven/commit/726ce892c49ba40d82b7982ee67ca87ee58848af

**Comment by jrmartin** [comment]
@mattearnshaw Awesome! Thanks

**Comment by jrmartin** [comment]
@mattearnshaw i think the wrong jar made it to the org.geppetto.maven repo. The jar won't open and a corrupted error opens up in windows. it's also only 11k b and previous version jar 3.0.5 was around 4mb.

**Comment by mattearnshaw** [comment]
@jrmartin looks OK to me? 3.97 MB https://github.com/openworm/org.geppetto.maven/blob/mvn-repo/com/dropbox/core/dropbox-core-sdk/3.0.6-SNAPSHOT/dropbox-core-sdk-3.0.6-SNAPSHOT.jar

**Comment by jrmartin** [comment]
@mattearnshaw i see. Strange. My eclipse is playing games with me with an 11 kb version.

**Pull request merged**
