### PR TITLE
Commenting jaxb force rebuild: causes endless-build loop in Eclipse. 

### PR DESCRIPTION
**Pull request by borismarin**
@tarelli it fixes it for me in Luna, and apparently for @adrianq in Juno.
SPH also needs to be updated accordingly.

### CODE REVIEW

**Comment by gidili** [comment]
@borismarin if this works I am sending you a beer :beer:

**Comment by borismarin** [comment]
@gidili where's my beer?

**Comment by gidili** [comment]
It's coming soon.

**Comment by borismarin** [comment]
Taking the tube ;)

**Pull request merged**
