### PR TITLE
Feature/325

### PR DESCRIPTION
**Pull request by jrmartin**
Updates jackson libraries to 2.10.3. 
Needed for https://github.com/OpenSourceBrain/geppetto-osb/issues/325

### CODE REVIEW

**Comment by jrmartin** [comment]
Passing travis build using this geppetto core branch, NeuroML dependencias at 1.5.3a
https://travis-ci.org/github/openworm/geppetto-application/builds/698978171

**Review by filippomc — COMMENTED** [review]
@jrmartin if I remember this didn't solve the problem at the end. Do you think merging this will still be beneficial?

**Comment by jrmartin** [comment]
@filippomc It didn't fix the issue https://github.com/OpenSourceBrain/geppetto-osb/issues/325, it would be useful to merge since it updates Jackson libraries and future neuroML releases might benefit from it.

**Review by filippomc — APPROVED** [review]
@tarelli ready to merge.

**Pull request merged**
