### PR TITLE
allow resolve one import type

### PR DESCRIPTION
**Pull request by mattearnshaw**
need to finally get the branch mess sorted...

this one is easy, we need this one to avoid crashing frontend when resolving many paths. see 
- https://github.com/openworm/org.geppetto.frontend/issues/717
and
- https://github.com/openworm/org.geppetto.frontend/commit/acb48971e7b0f082aee7dabccbbb6cbd7d9d5c61

(there will be a corresponding geppetto-client PR)

### CODE REVIEW

**Comment by tarelli** [comment]
@mattearnshaw what's the latest with this?

**Comment by mattearnshaw** [comment]
@tarelli this should be fine to merge. the change in geppetto-client will come later

**Review by tarelli — CHANGES_REQUESTED** [review]
@mattearnshaw could we do without this change?

**Comment by mattearnshaw** [comment]
@tarelli actually I'm pretty sure this was intentional... you were (I think) suggesting to change batch size to 1 in the frontend ([here](https://github.com/openworm/geppetto-client/blob/master/js/geppettoModel/model/Library.js#L65)), but at some point I modified this mechanism but kept the batching n=50 (will be part of the geppetto-client PR). Reason being I think because of a latency between client and server that adds up if making many requests in the frontend. Will try and confirm this with an example...

**Comment by tarelli** [comment]
@mattearnshaw so you don't need this right? if you are using batch = 50 definitely you don't need the other signature

**Comment by mattearnshaw** [comment]
@tarelli well this thinking was/is that it would still be needed. batch has always been 50, but when backend was using those batches the frontend would crash because "too much data was received at once". still testing this though...

**Comment by tarelli** [comment]
@mattearnshaw I don't follow why it would be needed, you can go down all the way to one if you want, why to have a different signature?

**Pull request closed without merging**
